// Branded Types and Validators
export {
  type Brand,
  type SessionId,
  type RunId,
  type ExecutionId,
  type TaskId,
  type WorkspaceId,
  type ContainerId,
  type UserId,
  type RuntimeIdentity,
  type PlatformUserId,
  type RequestId,
  type SpaceId,
  type ArtifactId,
  type RuntimeWorkspaceSegment,
  type SessionSeq,
  type SessionLogOffset,
  MAX_ID_LENGTH,
  isValidIdFormat,
  isValidPlatformUserId,
  isValidRuntimeIdentity,
  isValidRuntimeWorkspaceSegment,
  isValidSessionSeq,
  isValidSessionLogOffset,
  CANONICAL_PLATFORM_USER_ID_PATTERN,
  RUNTIME_IDENTITY_PATTERN,
  RUNTIME_WORKSPACE_SEGMENT_PATTERN,
  makeBranded,
  parseBranded,
  makeSessionId,
  makeRunId,
  makeExecutionId,
  makeTaskId,
  makeWorkspaceId,
  makeContainerId,
  makeUserId,
  makeRuntimeIdentity,
  makePlatformUserId,
  makeRuntimeWorkspaceSegment,
  makeSessionSeq,
  parseSessionSeq,
  makeSessionLogOffset,
  parseSessionLogOffset,
  parseRuntimeIdentity,
  parsePlatformUserId,
  parseRuntimeWorkspaceSegment,
  makeRequestId,
  makeSpaceId,
  makeArtifactId,
} from './branded.js';

// Errors and Envelopes
export {
  ProtocolErrorCode,
  type ErrorDetail,
  type ErrorPayload,
  type ErrorEnvelope,
  type SuccessEnvelope,
  type ApiEnvelope,
  isErrorEnvelope,
  isSuccessEnvelope,
  createSuccessEnvelope,
  createErrorEnvelope,
  ProtocolError,
} from './errors.js';

// Strict JSON parsing and serialization
export {
  DEFAULT_JSON_LIMITS,
  type JsonParseOptions,
  JsonParseError,
  JsonLimitExceededError,
  strictJsonParse,
  strictJsonStringify,
  type SessionSeedReceipt,
  canonicalJsonStringify,
  computeSessionEventsChecksum,
  computeSessionSeedReceipt,
  normalizeCanonicalSessionEvents,
  findFirstJsonMismatch,
} from './json.js';

// Cross-process Wire Types and Constants
export {
  ProtocolHeaders,
  type ProtocolHeaderName,
  type LogicalSessionHeader,
  type SessionHeader,
  type ContainerState,
  type RunStatus,
  type LogLevel,
  type ContainerHandshakeRequest,
  type ContainerHandshakeResponse,
  type ContainerHeartbeatRequest,
  type ContainerHeartbeatResponse,
  type ContainerTeardownRequest,
  type ContainerTeardownResponse,
  type RunStateChangeEvent,
  type RunLogEntry,
  type RunLogBatchRequest,
  type RunLogBatchResponse,
  type ApprovalRequestPayload,
  type ApprovalDecisionPayload,
  type ContainerEventEnvelope,
  type RpcRequestEnvelope,
  type RpcResponseEnvelope,
  MAX_MESSAGE_ATTACHMENTS,
  MAX_ATTACHMENT_DISPLAY_NAME_LENGTH,
  type MessageAttachmentRequestItem,
  type CanonicalAttachment,
  type PublicMessageAttachment,
  type RuntimeFallbackTarget,
  type McpRiskLevel,
  type McpToolPolicy,
  type McpServerPlan,
  type EffectiveMcpPlan,
  type MemoryInjectionMode,
  type MemoryPlan,
  type RuntimeMountSpec,
  type ExtensionSkillContributionActivation,
  type ExtensionMcpContributionActivation,
  type ExtensionCliContributionActivation,
  type ExtensionDshPluginContributionActivation,
  type ExtensionContributionActivation,
  type ExtensionActivationPlan,
  validateExtensionActivationPlan,
  type RuntimeTurnRequest,
} from './wire.js';
